// Generated by CoffeeScript 1.11.1

/*
 * Drawing Controller for Future Dystopia Project.
 *
 * Adapted by Bryce Summers on 4.15.2017
 * 
 * This class renders the current state of the game as represented in the passed in state controller.
 */

(function() {
  FDP.Color = (function() {
    function Color(r1, g1, b1) {
      this.r = r1;
      this.g = g1;
      this.b = b1;
    }

    Color.prototype.toInt = function() {
      var blue, green, red;
      red = Math.floor(this.r * 255);
      green = Math.floor(this.g * 255);
      blue = Math.floor(this.b * 255);
      red = red << 16;
      green = green << 8;
      return red + green + blue;
    };

    Color.prototype.add = function(c) {
      var b, g, r;
      r = this.r + c.r;
      g = this.g + c.g;
      b = this.b + c.b;
      return new FDP.Color(r, g, b);
    };

    Color.prototype.mult = function(c) {
      var b, g, r;
      r = this.r * c.r;
      g = this.g * c.g;
      b = this.b * c.b;
      return new FDP.Color(r, g, b);
    };

    Color.prototype.multScalar = function(p) {
      var b, g, r;
      r = this.r * p;
      g = this.g * p;
      b = this.b * p;
      return new FDP.Color(r, g, b);
    };

    return Color;

  })();

}).call(this);
