// Generated by CoffeeScript 1.11.1

/*
 * Story Controller for Future Dystopia Project.
 *
 * Written by Bryce Summers on Apr.24.2017
 * 
 * This class handles the button and Story text update logic throughout the game.
 * Note: Dimensions of room are 1200px by 800 px.
 */

(function() {
  FDP.Controller_Story = (function() {
    function Controller_Story(ui, draw) {
      this.ui = ui;
      this.draw = draw;
      this._active = true;
      this.p_left = this.newCircle(200, 700);
      this.p_mid = this.newCircle(600, 700);
      this.p_right = this.newCircle(1000, 700);
      this.p_up = this.newCircle(600, 200);
      this.p_down = this.newCircle(600, 600);
      this.current_narrative_audio = null;
      this.buttons = [];
      this.advance_func = this.click(this);
      this.make_story();
      this.advance_func();
    }

    Controller_Story.prototype.click = function(self) {
      return function() {
        var b, img, j, len, pline, ref, story;
        play(sounds.button);
        ref = self.buttons;
        for (j = 0, len = ref.length; j < len; j++) {
          b = ref[j];
          self.removeButton(b);
        }
        if (self.story_index >= self.story.length) {
          return;
        }
        story = self.story[self.story_index];
        self.story_index += 1;
        if (story.mid) {
          img = story.mid;
          pline = self.p_mid;
          b = self.ui.createButton(pline, self.advance_func, img);
          self.buttons.push(b);
        }
        if (story.left) {
          img = story.left;
          pline = self.p_left;
          b = self.ui.createButton(pline, self.advance_func, img);
          self.buttons.push(b);
        }
        if (story.right) {
          img = story.right;
          pline = self.p_right;
          b = self.ui.createButton(pline, self.advance_func, img);
          self.buttons.push(b);
        }
        if (story.up) {
          img = story.up;
          pline = self.p_up;
          b = self.ui.createButton(pline, self.advance_func, img);
          self.buttons.push(b);
        }
        if (story.down) {
          img = story.down;
          pline = self.p_down;
          b = self.ui.createButton(pline, self.advance_func, img);
          self.buttons.push(b);
        }
        if (story.header) {
          header.innerHTML = story.header;
        }
        if (story.statement) {
          instructions.innerHTML = story.statement;
        }
        if (story.audio) {
          if (self.current_narrative_audio !== null) {
            self.current_narrative_audio.pause();
          }
          if (story.audio !== null) {
            play(story.audio);
            self.current_narrative_audio = story.audio;
          }
        }
        if (story.background) {
          return self.draw.setBackground(story.background);
        }
      };
    };

    Controller_Story.prototype.make_story = function() {
      this.story = [];
      this.story_index = 0;

      /*
      s_birth = {mid:img_cry, header:"Birth", statement: "You were born into this world."}
      @story.push(s_birth)
      s_birth = {left:img_cry, header:"Birth", statement: "You were born into this world."}
      @story.push(s_birth)
      s_birth = {up:img_cry, header:"Birth", statement: "You were born into this world."}
      @story.push(s_birth)
      s_birth = {down:img_cry, header:"Birth", statement: "You were born into this world."}
      @story.push(s_birth)
       */
      this.story.push({
        left: img_cry,
        mid: img_cry,
        right: img_cry,
        header: "Birth",
        statement: "I was born into society in 2103.",
        audio: sounds.intro,
        background: bg_birth
      });
      this.story.push({
        left: img_cry,
        mid: img_cry,
        right: img_cry,
        header: "Mother's Death",
        statement: "My Mom died and was buried in a Government Beureu or external standards graveyard.",
        audio: sounds.mother_died,
        background: bg_cemetary_mainstream
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "Artist Graveyard",
        statement: "On my way out I passed by the artist graveyard...",
        audio: sounds.musings_from_the_cradle,
        background: bg_cemetary_artists
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "High School",
        statement: "I enrolled in a STEM centered High School.",
        audio: sounds.stem_school,
        background: bg_highschool
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "railroad",
        statement: "I had a fantasy about working for the railroad. It would have increased my physical difficulty multiplier.",
        audio: sounds.sixteen_tons,
        background: bg_railroad
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "college",
        statement: "I took the sensible route and enrolled in college to increase my mental difficulty multiplier.",
        audio: sounds.the_path_of_logic_and_math,
        background: bg_railroad
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "Professional IT worker",
        statement: "After graduating college, I became an IT worker at an ethical defense contracter located in Manhattan.",
        audio: sounds.number_crunching,
        background: bg_professional
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "A plead for the homeless.",
        statement: "After graduating college, I became an IT worker at an ethical defense contracter.",
        audio: sounds.plead_for_the_homeless,
        background: bg_homeless
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "Dream from Mom",
        statement: "A dream from my mother told me to remember the dreams that I had.",
        audio: sounds.stay_close_to_your_dreams,
        background: bg_dreams
      });
      this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "Older Years",
        statement: "From then on, I became an artist and tried to make a unique contribution to the world. I reflected on my life.",
        audio: sounds.thank_the_lord,
        background: bg_old_age
      });
      return this.story.push({
        left: img_todo,
        mid: img_todo,
        right: img_todo,
        header: "My Funeral",
        statement: "I died and was buried in the artist cemetary. A disgrace on the outside, but a fullfilled human being on the inside.",
        audio: sounds.mother_died_reprise,
        background: bg_old_age
      });
    };

    Controller_Story.prototype.newCircle = function(x, y) {
      var cx, cy, i, j, pts, radius, ref, ref1;
      pts = [];
      for (i = j = 0, ref = Math.PI * 2, ref1 = Math.PI / 100; ref1 > 0 ? j < ref : j > ref; i = j += ref1) {
        cx = x;
        cy = y;
        radius = 48;
        pts.push(new BDS.Point(cx + radius * Math.cos(i), cy + radius * Math.sin(i)));
      }
      return new BDS.Polyline(true, pts, true);
    };

    Controller_Story.prototype.removeButton = function(b) {
      return this.ui.removeButton(b);
    };

    Controller_Story.prototype.setActive = function(isActive) {
      return this._active = isActive;
    };

    Controller_Story.prototype.isActive = function() {
      return this._active;
    };

    Controller_Story.prototype.mouse_down = function(event) {};

    Controller_Story.prototype.mouse_up = function(event) {};

    Controller_Story.prototype.mouse_move = function(event) {};

    Controller_Story.prototype.time = function(dt) {};

    Controller_Story.prototype.window_resize = function(event) {};

    return Controller_Story;

  })();

}).call(this);
